name: Rust CI

on:
  workflow_call:
    inputs:
      working-dir:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  # Run cargo test
  test:
    name: Runs Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ github.event.runner.os }}-cargo-test-${{ hashFiles('${ github.event.inputs.working-dir }/Cargo.toml') }}
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run cargo test
        working-directory: ${{ github.event.inputs.working-dir }}
        run: cargo test

  # Run cargo clippy -- -D warnings
  clippy_check:
    name: Check Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ github.event.runner.os }}-cargo-clippy-${{ hashFiles('${ github.event.inputs.working-dir }/Cargo.toml') }}
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Run clippy
        working-directory: ${{ github.event.inputs.working-dir }}
        run: cargo clippy -- -D warnings

  # Run cargo fmt --all -- --check
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Run cargo fmt
        working-directory: ${{ github.event.inputs.working-dir }}
        run: cargo fmt --all -- --check
