services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: host
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    volumes:
      - .:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: host
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
    prom_data:
    grafana_data:
