[package]
name = "playground_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = "0.15"
bevy_ecs = "0.15"
bevy_log = "0.15"
wasm-bindgen = "0.2"
