# fly.toml app configuration file generated for learnbevy on 2024-10-21T19:38:38+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'learnbevy'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
