[package]
name = "check_crate_updates"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo_toml = "0.20.3"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
ureq = { version = "2.10.0", features = ["json"] }
