[package]
name = "rustfmt_api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.35", features = ["rt-multi-thread", "macros", "process"] }
warp = { version = "0.3", features = ["compression"] }
