[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_kira_audio = "0.17.0"
bevy_mod_picking = "0.16.0"
bevy_prototype_lyon = "0.9.0"
bevy_xpbd_2d = "0.2.0"
bevy_xpbd_3d = "0.2.0"
leafwing-input-manager = "0.10.0"
rand = "0.8"
rand_chacha = "0.3"
wasm-bindgen = "0.2"

[dependencies.bevy]
version = "0.11"
features = [
    "animation",
    "bevy_asset",
    "bevy_audio",
    "bevy_gilrs",
    "bevy_scene",
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_gltf",
    "bevy_render",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "png",
    "hdr",
    "ktx2",
    "zstd",
    "vorbis",
    "bevy_gizmos",
    "tonemapping_luts",
    "default_font",
    "webgl2",
]
default-features = false

[profile.release]
debug = false
lto = false
debug-assertions = false
codegen-units = 1
strip = "debuginfo"

[profile.release.package."*"]
opt-level = "z"
