[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13", default-features = false, features = [
    "animation",
    "bevy_asset",
    "bevy_audio",
    "bevy_gilrs",
    "bevy_scene",
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_gltf",
    "bevy_render",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "png",
    "hdr",
    "vorbis",
    "bevy_gizmos",
    "tonemapping_luts",
    "default_font",
    "webgl2",
] }

rand = "0.8"
rand_chacha = "0.3"

bevy_xpbd_2d = "0.4"
bevy_xpbd_3d = "0.4"
bevy_hanabi = "0.10"
bevy_mod_picking = "0.18"
bevy_prototype_lyon = "0.11"
bevy_kira_audio = "0.19"
leafwing-input-manager = "0.13"
bevy_dev = { version = "0.3", default-features = false }

wasm-bindgen = "0.2"

[profile.release.package."*"]
opt-level = 'z'

[profile.release]
debug = false
debug-assertions = false
lto = false
strip = "debuginfo"
codegen-units = 1
