[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", default-features = false, features = [
    "animation",
    "bevy_asset",
    "bevy_state",
    "bevy_audio",
    "bevy_color",
    "bevy_dev_tools",
    "bevy_gilrs",
    "bevy_scene",
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_gltf",
    "bevy_render",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "png",
    "hdr",
    "vorbis",
    "bevy_gizmos",
    "tonemapping_luts",
    "default_font",
    "webgl2",
] }

rand = "0.8.5"
rand_chacha = "0.3.1"

avian2d = "=0.1.1"
avian3d = "=0.1.1"
bevy_mod_picking = "=0.20.1"
bevy_prototype_lyon = "=0.12.0"
bevy_kira_audio = "=0.20.0"
leafwing-input-manager = "=0.14.0"
bevy_light_2d = "=0.2.1"
#bevy_dev = { version = "0.3.0", default-features = false }

wasm-bindgen = "0.2"

[profile.release.package."*"]
opt-level = 'z'

[profile.release]
debug = false
debug-assertions = false
lto = false
strip = "debuginfo"
codegen-units = 1
