[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", features = [ "bevy_dev_tools" ] }
wasm-bindgen = "=0.2.100"

rand = "0.8.0"

playground_lib = { git = "https://github.com/liamgallagher737/learnbevy.git" }

[profile.release.package."*"]
opt-level = 'z'

[profile.release]
debug = false
debug-assertions = false
lto = false
strip = "debuginfo"
codegen-units = 1
