[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", default-features = false, features = [
    "animation",
    "bevy_asset",
    "bevy_audio",
    "bevy_color",
    "bevy_gilrs",
    "bevy_scene",
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_gltf",
    "bevy_render",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "png",
    "hdr",
    "vorbis",
    "bevy_gizmos",
    "tonemapping_luts",
    "default_font",
    "webgl2",
] }
wasm-bindgen = "0.2"

[profile.release.package."*"]
opt-level = 'z'

[profile.release]
debug = false
debug-assertions = false
lto = false
strip = "debuginfo"
codegen-units = 1
