name: Compile Server OS CI (nix)
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Dry Run OS Build
      working-directory: ./compile_server_os
      run: nix run github:nix-community/nixos-anywhere -- --flake .#host-eons-hss1 --vm-test
