name: Compile Server OS CI (nix)

on:
  push:
    branches: [main]
    paths:
    - 'compile_server_os/**'
    - '.github/workflows/compile-server-os-ci.yml'
  pull_request:
    branches: [main]
    paths:
    - 'compile_server_os/**'
    - '.github/workflows/compile-server-os-ci.yml'


jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machine: [mi]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Dry Run OS Build
      working-directory: ./compile_server_os
      run: nix run github:nix-community/nixos-anywhere -- --flake .#${{ matrix.machine }} --vm-test
