name: Images CI

on:
  push:
    branches: [main]
    paths:
    - 'images/**'
    - '.github/workflows/images-ci.yml'
  pull_request:
    branches: [main]
    paths:
    - 'images/**'
    - '.github/workflows/images-ci.yml'

jobs:
  build:
    name: Checking ${{ matrix.version }} on ${{ matrix.channel }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - main
          - 0.13
          - 0.12
          - 0.11
          - 0.10
        channel:
        - stable
        - nightly
    env:
      IMAGE_NAME: ${{ github.sha }}-${{ matrix.version }}-${{ matrix.channel }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:v0.11.6

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: images
          file: images/Dockerfile
          build-args: |
            version=${{ matrix.version }}
            channel=${{ matrix.channel }}
          push: false
          cache-from: type=gha,scope=${{ matrix.version }}-${{ matrix.channel }}
          cache-to: type=gha,scope=${{ matrix.version }}-${{ matrix.channel }},mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
