name: Update Compile Server

on:
  push:
    branches: [main]
    paths:
    - 'compile_api/**'
    - 'compile_server_os/**'
    - '.github/workflows/compile-server-os-ci.yml'
  pull_request: # for testing

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-server:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - name: Set up Nix
      uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Update Server
      working-directory: ./compile_server_os
      run: nix run nixpkgs#nixos-rebuild -- --flake .#host-eons-slc --target-host root@slc.compile.learnbevy.com switch
