name: Website CI

on:
  push:
    branches: [main]
    paths:
    - 'www/**'
    - '.github/workflows/www-ci.yml'
  pull_request:
    branches: [main]
    paths:
    - 'www/**'
    - '.github/workflows/www-ci.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Check
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run check
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Format
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run lint
