name: Website CI

on:
  push:
    branches: [main]
    paths:
    - 'www/**'
    - '.github/workflows/www-ci.yml'
  pull_request:
    branches: [main]
    paths:
    - 'www/**'
    - '.github/workflows/www-ci.yml'

jobs:
  svelte:
    runs-on: ubuntu-latest
    name: Check Svelte
    steps:
      - uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: Install Dependencies
        working-directory: www
        run: deno install
      - name: Check
        working-directory: www
        run: deno task check

  lint:
    runs-on: ubuntu-latest
    name: Check Lints
    steps:
      - uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: Install Dependencies
        working-directory: www
        run: deno install
      - name: Check
        working-directory: www
        run: deno run --allow-all npm:oxlint@0.9.10 -f github --deny-warnings

  format:
    runs-on: ubuntu-latest
    name: Check Formatting
    steps:
      - uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: Install Dependencies
        working-directory: www
        run: deno install
      - name: Check
        working-directory: www
        run: deno fmt --check
