name: Website CI

on:
  push:
    branches: [main]
    paths:
    - 'www/**'
    - '.github/workflows/www-ci.yml'
  pull_request:
    branches: [main]
    paths:
    - 'www/**'
    - '.github/workflows/www-ci.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    name: Run Check
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependencies
        working-directory: www
        run: npm ci
      - name: Check
        working-directory: www
        run: npm run check
  format:
    runs-on: ubuntu-latest
    name: Check Formatting
    steps:
      - uses: actions/checkout@v4
      - name: Setp
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependencies
        working-directory: www
        run: npm ci
      - name: Check
        working-directory: www
        run: npx prettier --check .
